### ISSUE TITLE
New Beam API Changes Broke Beam Caht

### ISSUE THREAD

**Issue by Draygera** [xedoc/Ubiquitous2#19]
http://forums.beam.pro/topic/87/heads-up-developers

**Comment by xedoc** [comment]
Thanks for heads up. I will fix it

**Comment by Draygera** [comment]
Haven't fully tested but chat is working again. Thanks. XD

**Comment by Draygera** [comment]
So far, so good. Ran for 3 hours and all emotes and everything else worked fine

**Comment by shufunk** [comment]
Dray and i have been using this program and I am currently having issues with beam. Both of us stream around the same time and when i start up the program beam is not working but his is! Quite annoying and i tried all remidies of disableing certain chats and even all chats but beam and still not working. My main audience is on beam and really need the chat working

**Comment by xedoc** [comment]
Will check it. What is your channel name there ?

**Comment by shufunk** [comment]
beam.pro/shufunk

**Comment by xedoc** [comment]
Should be fixed now.

**Comment by shufunk** [comment]
I saw when I launched the program it downloaded a "patch" but still not working. even recorded me doing a fresh install and it's still doing what it's doing https://youtu.be/wFyPI1e2Ba0

**Comment by xedoc** [comment]
Interesting. Thats how it work on my end: http://i.imgur.com/MmCiHN2.gif

**Comment by shufunk** [comment]
Apparently I have come to a conclusion it's my laptop having issues. I installed on my musicbot PC and Ubiquitous2 works fine on it. I ended up opening the port on that PC and rerouted how i was accessing chat. This still bothers me that this has been hapening

**Comment by xedoc** [comment]
Please check your firewall rules(blacklist) for ubiquitous2.exe. It could be added there if you accidentally select Deny in the Allow network access dialog.
