### ISSUE TITLE
Gaming.tv Chat Not Working

### ISSUE THREAD

**Issue by Draygera** [xedoc/Ubiquitous2#5]
Idk how many messages I have missed because of this but apparently I can't get the Gaming.tv chat to work with your program. Do you have suggestions? Please and thank you.

**Comment by xedoc** [comment]
I'll check it. Probably they changed something in protocol...

**Comment by Draygera** [comment]
Thanks a lot. Also, how do you access the chat anyways, if you don't mind my asking, @xedoc? I'm asking because I'm currently starting to write my own custom chat bot that basically functions like something like Ankhbot but with multiple chats added to it. Thanks.

**Comment by xedoc** [comment]
Every chat is using its own communication method: websockets, http polling, irc. Unfortunately there is no general way to work with all of them...

**Comment by Draygera** [comment]
Thanks for getting back to me. I completely understand and am willing to work with such. Was mainly asking because Gaming.tv doesn't seem to have an open API. I'm mainly wanting to build my own custom bot for portfolio purposes and other stuff. Hobbyist programmer here. XD

**Comment by xedoc** [comment]
Gaming.tv should work now. Check it please

**Comment by Draygera** [comment]
Still no go for me. Attached are screenshots of my Ubiquitous and Gaming.tv websites. Going to restart computer and see if maybe this was a fluke.

![gaming tv](https://cloud.githubusercontent.com/assets/1167549/8654504/4a5e7130-2950-11e5-896b-048590ad0972.png)
![gaming tv 2](https://cloud.githubusercontent.com/assets/1167549/8654505/4a61a6de-2950-11e5-902a-20f2f0fbcf3c.png)

**Comment by Draygera** [comment]
Still not working after restart. Had to do this other day for Youtube to work. :/

**Comment by xedoc** [comment]
I will check it further. BTW now you can restart a chat with double click on a counter.

**Comment by Draygera** [comment]
I had already checked that out. It's possible it could still be my end. Just found out a few of my drivers were corrupted and I'm having to restore them before I can go any further. :/

**Comment by xedoc** [comment]
Could be. Because on my side it works perfectly:
![Screenshot](http://i.imgur.com/cykOnmx.png)

**Comment by Draygera** [comment]
Update: I won't be able to test it out any further tonight due to my power supply shorting out. I had to go to Best Buy and get a new one. I'm having to reinstall windows because it became too corrupted to boot. Will be testing it out tomorrow. Thanks for all of your hard work, xedoc. You have such an awesome program. xD

**Comment by Draygera** [comment]
I said I wasn't going to test anymore tonight, but I had a little bit of time. Still not working at all for me. Have any suggestions? I know, when GamingLive.tv was first added there seemed to have been a problem with having your username in upper / lowercase causing me to not be able to login. At least that was my experience at first. Maybe the same problem?

**Comment by xedoc** [comment]
Yes you right. The problem was the proper character case in channel name. Please try to specify Draygera (first capital) in channels field or in the user name.

**Comment by Draygera** [comment]
Here are three pictures, all with varying versions of upper / lowercase usernames / channels.
![gaming tv](https://cloud.githubusercontent.com/assets/1167549/8679170/ee12f0cc-2a0d-11e5-93de-1e7c0f5187d4.PNG)
![gaming tv2](https://cloud.githubusercontent.com/assets/1167549/8679284/959619c8-2a0e-11e5-9a4f-9947f473cea4.PNG)
![gaming tv3](https://cloud.githubusercontent.com/assets/1167549/8679250/60dcd1cc-2a0e-11e5-917d-776a1604d360.PNG)

So, it does work now but also opens up two channels when the channel name is lower case. It's not a huge issue for me but cosmetically it might be one for other users.

**Comment by xedoc** [comment]
Well thats how it mean to be. Draygera and draygera are different channels for gaming.tv. So to prevent duplicates you need to specify both channel name and user name in same case. Or fill in your username with first capital and don't specify channel name at all.

**Comment by Draygera** [comment]
That makes sense then. Thanks for the input. Sounds like how Linux and Mac naming conventions work.

**Comment by xedoc** [comment]
Yep exactly ;)
